config/routes.rb
CampUS::Application.routes.draw do

  
  get "users/new"
  resources :activities
  resources :users

  root 'activities#show' #este es el rooteo de la pagina. Muy util. Cambiar por home page.
 
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'

  
  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
    has_many :users
	  
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :activities
	before_save { self.email = email.downcase }
	before_create :create_remember_token


	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false } #true 	
  	has_secure_password
  	validates :password, length: { minimum: 6 }

  	def User.new_remember_token
	    SecureRandom.urlsafe_base64
	  end

	  def User.digest(token)
	    Digest::SHA1.hexdigest(token.to_s)
	  end

	  private

	    def create_remember_token
	      self.remember_token = User.digest(User.new_remember_token)
	    end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
    before_filter :except => [:show, :index, :set_activity] do require_admin end

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
    @user = current_user
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
      @activity.id_creator = current_user.name
    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @activity }
      else
        format.html { render action: 'new' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      begin
        @activity = Activity.find(params[:id])
        rescue ActiveRecord::RecordNotFound
          redirect_to "/activities"
      end 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:id_activity, :id_creator, :id_location, :name, :date, :duration, :cathegory, :description, :privacy)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
    
 end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	  end

	  def create
	  	user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
		    sign_in user
      		redirect_to user
		else
		   flash.now[:error] = 'Invalid email/password combination'
      	   render 'new'
		end
	  end

	  def destroy
	  	sign_out
    	redirect_to root_url
	  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]
    
  #def new
  #end #original controller
  def index
      @users = User.order(:name)
      
      respond_to do |format|
          format.html # index.html.erb
          format.xml { render :xml => @users }
      end
  end

  def show

  end

  def new
  	@user = User.new
  	if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
  		redirect_to @user, :notice => "Successfully signed up."
  	else
  		render "new"
  	end
  end

  def destroy
      if session[:user_id] != @user[:id]
          flash[:notice] = "Sorry you can not"
          redirect_to "/users"
      else
  	@user.destroy
    redirect_to "/users"
      end
  end

  def update
  	respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  	def set_user
      begin
        @user = User.find(params[:id])
        rescue ActiveRecord::RecordNotFound
          redirect_to "/users"
      end 
    end
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end	
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
	    remember_token = User.new_remember_token
	    cookies.permanent[:remember_token] = remember_token
	    user.update_attribute(:remember_token, User.digest(remember_token))
	    self.current_user = user
	  end

	def signed_in?
	    !current_user.nil?
	  end

	def current_user=(user)
       @current_user = user
    end

    def current_user
	    remember_token = User.digest(cookies[:remember_token])
	    @current_user ||= User.find_by(remember_token: remember_token)
	  end
	  def sign_out
	    current_user.update_attribute(:remember_token,
	                                  User.digest(User.new_remember_token))
	    cookies.delete(:remember_token)
	    self.current_user = nil
	  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <!--id activity y id creator no deben ser desplegados en la form. Deben ser producidos por el controller -->

    <!-- <div class="field">
      <%= f.label :id_activity %><br>
      <%= f.text_field :id_activity %>
    </div>
  -->
   
    
    <!-- es solo un reminder importante -->

  <div class="field">
    <%= f.label :id_location %><br>
    <%= f.text_field :id_location %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :cathegory %><br>
    <%= f.text_field :cathegory %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :rows => 15 %>
  </div>
  <div class="field">
    <%= f.label :privacy %><br>
    <%= f.check_box :privacy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p><%= link_to 'User List', users_path %></p>
<signin><%= link_to 'Sign In!', new_session_path %></signin>
<signup><%= link_to 'Not a user yet?', new_user_path %></signup>
<h1>Current Activities</h1>

<table>
  <thead>
    <tr>
      <th>Id creator</th>
      <th>Id location</th>
      <th>Name</th>
      <th>Date</th>
      <th>Duration</th>
      <th>Cathegory</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.id_creator %></td>
        <td><%= activity.id_location %></td>
        <td><%= activity.name %></td>
        <td><%= activity.date %></td>
        <td><%= activity.duration %></td>
        <td><%= activity.cathegory %></td>
        <td><%= activity.description %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id activity:</strong>
  <%= @activity.id %>
</p>

<p>
<creator>
  <strong>Id creator:</strong>
  <%= @activity.id_creator %>
</creator>
</p>

<p>
<loc>
  <strong>Id location:</strong>
  <%= @activity.id_location %>
</loc>
</p>

<p>
<event>
  <strong>Name:</strong>
  <%= @activity.name %>
</event>
</p>

<p>
<date>
  <strong>Date:</strong>
  <%= @activity.date %>
</date>
</P>

<p>
<duration>
  <strong>Duration:</strong>
  <%= @activity.duration %>
</duration>
</p>

<p>
<cat>
  <strong>Cathegory:</strong>
  <%= @activity.cathegory %>
</cat>
</p>

<p>
  <desc>
    <strong>Description:</strong>
    <%= @activity.description %>
  </desc>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CampUS</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render 'shared/error_messages' %>
  
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit "Create my account", class: "btn btn-large btn-primary"%></p>

<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>camp-USers</h1>
<% if notice %>
<p id="notice" ><%= notice %></p>
<% end %>

<table>
<tr>
<th>Name</th>
<th></th>
<th></th>
<th></th>
</tr>


<% @users.each do |user| %>
<tr>
<td><%= user.name %></td>
<td><%= link_to 'Show' , user %></td>
<td><%= link_to 'Edit' , edit_user_path(user) %></td>
<td><%= link_to 'Destroy' , user, :confirm => 'Are you sure?' ,
:method => :delete %></td>
</tr>
<% end %>
</table>
<br />
<%= link_to 'New User' , new_user_path %>
<p><%= link_to 'Back to Activity List', activities_path %></p>

app/views/users/new.html.erb
<h1>Welcome to campUS</h1>
<h2><strong>Please sign up</strong></h2>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1><strong><%= @user.name %><strong></h1> 

<p><%= @user.email %></p>

<p><t>camp-USer since: </t><%= @user.created_at %></p>

<%= link_to 'Back to User List', users_path %>